I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 308, in script
    jump ch4_plot1
ScriptError: could not find label 'ch4_plot1'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 308, in script
    jump ch4_plot1
  File "/Applications/RenPy/renpy-8.3.7-sdk/renpy/ast.py", line 1712, in execute
    rv = renpy.game.script.lookup(target)
  File "/Applications/RenPy/renpy-8.3.7-sdk/renpy/script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'ch4_plot1'.

macOS-14.3.1-arm64-arm-64bit arm64
Ren'Py 8.3.7.25031702
Adventurer 1.0
Sun Jul  6 22:59:56 2025
